"use client";
import { useState } from "react";
import { ArrowRight, CalendarDays } from "lucide-react";
import { useSite } from "./site-provider";
export function ContactForm() {
  const [sent, setSent] = useState(false);
  const { locale } = useSite();
  const filloutId = process.env.NEXT_PUBLIC_FILLOUT_FORM_ID;
  if (filloutId) return <div className="contact-layout"><iframe className="fillout-frame" title="Contact and scheduling form" src={`https://form.fillout.com/t/${encodeURIComponent(filloutId)}?embed=true`} loading="lazy" /><aside><CalendarDays size={26} /><h2>{locale === "en" ? "Thirty useful minutes." : "Faydalı otuz dakika."}</h2><p>Google Meet · Europe/Istanbul<br />{locale === "en" ? "24-hour notice · 2-week horizon" : "24 saat önceden · 2 haftalık aralık"}</p><span>{locale === "en" ? "Scheduling is offered conditionally for collaboration and business inquiries." : "Planlama, iş birliği ve iş taleplerinde koşullu olarak sunulur."}</span></aside></div>;
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(`[iesy.me] ${data.get("reason")} — ${data.get("name")}`); const body = encodeURIComponent(`${data.get("message")}\n\nFrom: ${data.get("name")} <${data.get("email")}>`); window.location.href = `mailto:i.efeyesildag@gmail.com?subject=${subject}&body=${body}`; setSent(true);
  };
  return <div className="contact-layout"><form className="contact-form" onSubmit={submit}><label>{locale === "en" ? "Name" : "Ad"}<input name="name" required autoComplete="name" /></label><label>E-posta<input name="email" required type="email" autoComplete="email" /></label><label>{locale === "en" ? "Reason" : "Konu"}<select name="reason" defaultValue="collaboration"><option value="collaboration">{locale === "en" ? "Collaboration" : "İş birliği"}</option><option value="business">{locale === "en" ? "Business" : "İş"}</option><option value="feedback">{locale === "en" ? "Feedback" : "Geri bildirim"}</option><option value="other">{locale === "en" ? "Other" : "Diğer"}</option></select></label><label>{locale === "en" ? "Message" : "Mesaj"}<textarea name="message" required rows={6} /></label><button className="primary-button">{locale === "en" ? "Prepare message" : "Mesajı hazırla"} <ArrowRight size={18} /></button>{sent && <p className="form-note">{locale === "en" ? "Your email app should now be open. Connect Fillout to enable conditional scheduling." : "E-posta uygulaman açılmış olmalı. Koşullu planlamayı etkinleştirmek için Fillout’u bağla."}</p>}</form><aside><CalendarDays size={26} /><h2>{locale === "en" ? "Thirty useful minutes." : "Faydalı otuz dakika."}</h2><p>Google Meet · Europe/Istanbul<br />{locale === "en" ? "24-hour notice · 2-week horizon" : "24 saat önceden · 2 haftalık aralık"}</p><span>{locale === "en" ? "Scheduling activates after a relevant inquiry." : "Planlama, uygun taleplerden sonra etkinleşir."}</span></aside></div>;
}
