"use client";
import { PageHeading } from "./page-heading";
import { useSite } from "./site-provider";
import type { Repository } from "@/lib/github";
import type { SiteContent } from "@/lib/site-schema";
export function NowExperience({ repositories, posts }: { repositories: Repository[]; posts: SiteContent["linkedinPosts"] }) {
  const { locale } = useSite();
  return <div className="page-wrap"><PageHeading index="03" eyebrow={{ en: "A LIVING LOG / AUGUST 2026", tr: "CANLI BİR GÜNLÜK / AĞUSTOS 2026" }} title={{ en: "What has my attention now.", tr: "Şu anda dikkatimi çekenler." }} body={{ en: "A readable stream of building, learning, and ideas in motion. GitHub updates automatically; LinkedIn notes are reviewed and published through the owner dashboard.", tr: "Üretmenin, öğrenmenin ve hareket hâlindeki fikirlerin okunabilir akışı. GitHub otomatik güncellenir; LinkedIn notları yönetim panelinden incelenip yayımlanır." }} /><div className="timeline-list">{posts.map((post, i) => <article key={post.id}><span>L{String(i + 1).padStart(2, "0")}</span><div><p className="eyebrow">LINKEDIN · {post.publishedAt}</p><h2>{post.title}</h2><p>{post.excerpt}</p>{post.taggedPeople.length > 0 && <div className="tag-cloud">{post.taggedPeople.map((person) => <span key={person}>{person}</span>)}</div>}{post.sources.length > 0 && <div className="source-links">{post.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</div>}</div><a href={post.url} target="_blank" rel="noreferrer">{locale === "en" ? "Original post" : "Özgün gönderi"} ↗</a></article>)}{repositories.map((repo, i) => <article key={repo.id}><span>{String(i + 1).padStart(2, "0")}</span><div><p className="eyebrow">GITHUB · {new Date(repo.pushed_at).toLocaleDateString(locale === "en" ? "en" : "tr")}</p><h2>{locale === "en" ? `Moved ${repo.name.replaceAll("_", " ")} forward.` : `${repo.name.replaceAll("_", " ")} projesini ileri taşıdım.`}</h2><p>{repo.description || (locale === "en" ? "An active repository received another iteration." : "Aktif bir depo yeni bir geliştirme aldı.")}</p></div><a href={repo.html_url} target="_blank" rel="noreferrer">{locale === "en" ? "Inspect repository" : "Depoyu incele"} ↗</a></article>)}</div></div>;
}
